# Generated by Django 5.1.7 on 2025-03-16 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('category', models.CharField(blank=True, choices=[('Essentials', 'Essentials'), ('Wants', 'Wants'), ('Investments', 'Investments'), ('Savings', 'Savings')], max_length=20, null=True)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('UPI', 'UPI'), ('SMS', 'SMS'), ('Manual', 'Manual')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
